// config.js : là où on cache les clés!
export const config = {
    infoclimat: {
        auth: 'AhgFEgB%2BASMFKAcwUCYHLgRsV2IBdwEmUCwDYAxpBXgGbVIzBWUBZwRqUi8AL1FnUn9VNgkyAzMKYVcvXy0FZAJoBWkAawFmBWoHYlB%2FBywEKlc2ASEBJlAyA2wMaQV4BmdSNQVnAX0EbVI1AC5RZFJhVT0JKQMkCmhXN182BWcCZgVpAGYBYQVrB2RQfwcsBDFXMAFqAThQOwNsDGYFNAZmUjAFYgFiBGtSNQAuUWJSaVU0CTQDOgpsVzBfNQV5An4FGAAQAX4FKgcnUDUHdQQqV2IBYAFt',
        c: 'd0a36ba3e5be34cc553d259e07db765f'
    }
};

